os: osx
osx_image: xcode10.1
branches:
  only:
    - master
language: swift

xcode_project: Clean Swift.xcodeproj

language: swift
osx_image: xcode10.1

cache:
  directories:
    - Carthage
    - Clean Swift/Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="Clean Swift.xcodeproj"
    - SCHEME_IOS="Clean Swift"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X"        SCHEME="$SCHEME_IOS" RUN_TESTS="YES" BUILD_EXAMPLE="YES" SDK="$IOS_SDK"
    - DESTINATION="OS=12.1,name=iPhone XS"       SCHEME="$SCHEME_IOS" RUN_TESTS="YES" BUILD_EXAMPLE="YES" SDK="$IOS_SDK"
    - DESTINATION="OS=11.4,name=iPhone X"        SCHEME="$SCHEME_IOS" RUN_TESTS="YES" BUILD_EXAMPLE="YES" SDK="$IOS_SDK"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="$SCHEME_IOS" RUN_TESTS="YES" BUILD_EXAMPLE="YES" SDK="$IOS_SDK"

before_install:
  #- brew update
  #- brew outdated carthage || brew upgrade carthage
  #- git submodule update --remote
  - bundle install
  - gem install license_finder
  - carthage bootstrap --cache-builds --no-use-binaries --platform iOS
  
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

git:
  depth: false
  quiet: true
