os: osx
branches:
  only:
    - master
language: swift

xcode_project: Clean Swift.xcodeproj

language: swift
osx_image: xcode10.1

cache:
  directories:
    - Carthage
    - Clean Swift/Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="Clean Swift.xcodeproj"
    - SCHEME_IOS="Clean Swift"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.1,name=iPhone XS"       SCHEME="$SCHEME_IOS" RUN_TESTS="YES" BUILD_EXAMPLE="YES" SDK="$IOS_SDK"

before_install:
  #- brew update
  #- brew outdated carthage || brew upgrade carthage
  #- git submodule update --remote
  #- gem install license_finder
  #- carthage bootstrap --cache-builds --no-use-binaries --platform iOS
  
script:
  - require 'bundler/setup'
  - xcodebuild -scheme Clean Swift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test

git:
  depth: false
  quiet: true
