//
//  ShowDetailMovieInteractor.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 11/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailMovieBusinessLogic
{
    func showDetailMovie()
}

protocol DetailMovieDataStore
{
    var detailMovie : MovieModel.Movie2! { get set }
}

class DetailMovieInteractor: DetailMovieBusinessLogic, DetailMovieDataStore
{
    var detailMovie: MovieModel.Movie2!
    
    var presenter: DetailMoviePresentationLogic?
    var worker: DetailMovieWorker?
    
    // MARK: Do something
    
    func showDetailMovie() {
        let response = DetailMovie.Something.Response(movie: detailMovie)
        presenter?.presentMovie(response: response)
    }
}
