//
//  ShowDetailMovieModels.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 11/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowDetailMovie
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var movie: MovieModel.Movie2
    }
    struct ViewModel
    {
        var movie: MovieModel.Movie2
    }
  }
}
