//
//  ShowDetailMoviePresenter.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 11/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailMoviePresentationLogic
{
    func presentMovie(response: ShowDetailMovie.Something.Response)
}

class ShowDetailMoviePresenter: ShowDetailMoviePresentationLogic
{
    weak var viewController: ShowDetailMovieDisplayLogic?
    
    // MARK: Do something
    
    func presentMovie(response: ShowDetailMovie.Something.Response) {
        let viewModel = ShowDetailMovie.Something.ViewModel(movie: response.movie)
        viewController?.displayDetailMovie(viewModel: viewModel)
    }
}
