//
//  ShowListMoviePresenter.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 05/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviePresenterOutput: class
{
    func displayUpcomingMovie(response: MovieModel.ViewModel)
    func displayNowPlayingMovie(response: MovieModel.ViewModel)
    func displayDetailMovie(response: MovieModel.ViewModel)
}

class ListMoviePresenter: ListMovieInteractorOutput
{
    weak var output: ListMoviePresenterOutput?
    
    // MARK: Presentation Logic
    
    func presentNowPlayingMovie(response: MovieModel.ViewModel) {
        let viewModel = MovieModel.ViewModel(listMovie: response.listMovie, movie: nil)
        output?.displayNowPlayingMovie(response: viewModel)
    }
    
    func presentUpcomingMovie(response: MovieModel.ViewModel) {
        let viewModel = MovieModel.ViewModel(listMovie: response.listMovie, movie: nil)
        output?.displayUpcomingMovie(response: viewModel)
    }
    
    func presentDetailMovie(response: MovieModel.ViewModel) {
        let viewModel = MovieModel.ViewModel(listMovie: nil, movie: response.movie)
        output?.displayDetailMovie(response: viewModel)
    }
    
}
