//
//  ShowListMovieViewController.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 05/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/**
 Class to control the table view of the scene.
 */
class ListMovieViewController: UIViewController
{
    var output: ListMovieInteractorInput!
    var router: ListMovieRouter!
    
    @IBOutlet weak var movieListTableView: UITableView!
    
    var movieHeader = ["Now Showing", "Upcoming"]
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    var upcomingMovie: [MovieModel.Movie2] = []
    var nowPlayingMovie: [MovieModel.Movie2] = []
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        ListMovieConfigurator.sharedInstance.configure(viewController: self)
        
        movieListTableView.register(UINib(nibName: "ListMovieTableViewCell", bundle: nil), forCellReuseIdentifier: "TableCell")
        movieListTableView.register(UINib(nibName: "HeaderTableViewCell", bundle: nil), forCellReuseIdentifier: "HeaderCell")
        movieListTableView.rowHeight            = UITableView.automaticDimension
        movieListTableView.estimatedRowHeight   = UITableView.automaticDimension
        
        getNowPlayingMovie()
        getUpcomingMovie()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.navigationBar.setBackgroundImage(UIImage(), for: .default)
        navigationController?.navigationBar.isTranslucent = true
        navigationController?.navigationBar.shadowImage = UIImage()
        navigationController?.navigationBar.backgroundColor = .clear
        
        self.navigationController?.navigationBar.backIndicatorImage = UIImage(named: "back")
        self.navigationController?.navigationBar.backIndicatorTransitionMaskImage = UIImage(named: "back")
        self.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: UIBarButtonItem.Style.plain, target: nil, action: nil)
        
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
    }
    
    // MARK: Do something
    
    func getUpcomingMovie(){
        output.getUpcomingMovie()
    }
    
    func getNowPlayingMovie(){
        output.getNowPlayingMovie()
    }
}

extension ListMovieViewController: ListMoviePresenterOutput {
    
    func displayUpcomingMovie(response: MovieModel.ViewModel) {
        upcomingMovie = response.listMovie!
        self.movieListTableView.reloadData()
    }
    
    func displayNowPlayingMovie(response: MovieModel.ViewModel) {
        nowPlayingMovie = response.listMovie!
        self.movieListTableView.reloadData()
    }
    
    func displayDetailMovie(response: MovieModel.ViewModel) {
        router?.routeToDetailMovie()
    }
    
}

extension ListMovieViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 4
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.row % 2 != 0 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "TableCell", for: indexPath) as! ListMovieTableViewCell
            if indexPath.row == 1 {
                cell.setupCell(listMovie: nowPlayingMovie)
            } else {
                cell.setupCell(listMovie: upcomingMovie)
            }
            cell.delegate = self
            cell.selectionStyle = .none
            return cell
        } else {
            let cell = tableView.dequeueReusableCell(withIdentifier: "HeaderCell", for: indexPath) as! HeaderTableViewCell
            cell.setupCell(movieHeader[indexPath.row/2])
            cell.selectionStyle = .none
            return cell
        }
    }
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if indexPath.row % 2 == 0 {
            return 44
        } else {
            return 440
        }
    }
    
}

extension ListMovieViewController: MovieSelection {
    func didSelectMovie(_ movie: MovieModel.Movie2) {
        output.showDetail(movie: movie)
    }
}
