//
//  ShowListMovieRouter.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 05/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListMovieRoutingLogic
{
    func routeToDetailMovie()
}

protocol ListMovieDataPassing
{
    var dataStore: ListMovieDataStore? { get }
}

class ListMovieRouter: NSObject, ListMovieRoutingLogic, ListMovieDataPassing
{
    weak var viewController: ListMovieViewController?
    var dataStore: ListMovieDataStore?
    
    // MARK: Routing

    func routeToDetailMovie(){
        let storyboard = UIStoryboard(name: "Movie", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailMovieVC") as! DetailMovieViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: ListMovieViewController, destination: DetailMovieViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: ListMovieDataStore, destination: inout DetailMovieDataStore)
    {
        destination.detailMovie = source.detailMovie
    }
}
