//
//  ShowListMoviePresenter.swift
//  Clean Swift
//
//  Created by Fabianus Hendy Evan on 05/04/19.
//  Copyright (c) 2019 Fabianus Hendy Evan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowListMoviePresentationLogic
{
    func presentUpcomingMovie(response: MovieModel.ViewModel)
    func presentNowPlayingMovie(response: MovieModel.ViewModel)
    func presentDetailMovie(response: MovieModel.ViewModel)
}

class ShowListMoviePresenter: ShowListMoviePresentationLogic
{
    weak var viewController: ShowListMovieDisplayLogic?
    
    // MARK: Do something
    
    func presentUpcomingMovie(response: MovieModel.ViewModel) {
        let viewModel = MovieModel.ViewModel(listMovie: response.listMovie, movie: nil)
        viewController?.displayUpcomingMovie(viewModel: viewModel)
    }
    
    func presentNowPlayingMovie(response: MovieModel.ViewModel) {
        let viewModel = MovieModel.ViewModel(listMovie: response.listMovie, movie: nil)
        viewController?.displayNowPlayingMovie(viewModel: viewModel)
    }
    
    func presentDetailMovie(response: MovieModel.ViewModel) {
        let viewModel = MovieModel.ViewModel(listMovie: nil, movie: response.movie)
        viewController?.displayDetailMovie(viewModel: viewModel)
    }
}
